// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATyzXyuRXcZUDvOuspt_D7D7bkm-_9Q1U',
    appId: '1:446843152706:web:e3c93885f7e63d018f80db',
    messagingSenderId: '446843152706',
    projectId: 'langvie',
    authDomain: 'langvie.firebaseapp.com',
    storageBucket: 'langvie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMqfdT92hQHYtigIDQL0NrUxHbWEPUtQ',
    appId: '1:446843152706:android:5f21fdcd144256748f80db',
    messagingSenderId: '446843152706',
    projectId: 'langvie',
    storageBucket: 'langvie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2IYSseqnCJYzRsB9n9KXWGxMjBn0lBk',
    appId: '1:446843152706:ios:d3ab8564746af9248f80db',
    messagingSenderId: '446843152706',
    projectId: 'langvie',
    storageBucket: 'langvie.firebasestorage.app',
    iosBundleId: 'com.example.langvie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2IYSseqnCJYzRsB9n9KXWGxMjBn0lBk',
    appId: '1:446843152706:ios:d3ab8564746af9248f80db',
    messagingSenderId: '446843152706',
    projectId: 'langvie',
    storageBucket: 'langvie.firebasestorage.app',
    iosBundleId: 'com.example.langvie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATyzXyuRXcZUDvOuspt_D7D7bkm-_9Q1U',
    appId: '1:446843152706:web:d26c6e8d2a3c81bb8f80db',
    messagingSenderId: '446843152706',
    projectId: 'langvie',
    authDomain: 'langvie.firebaseapp.com',
    storageBucket: 'langvie.firebasestorage.app',
  );
}
